message: "&cYou're not allowed to see our plugins!"
protected-commands:
  - "/pl"
  - "/plugins"
  - "/?"
  - "/bukkit:pl"
  - "/bukkit:?"
  - "/bukkit:plugins"
  - "/ver"
  - "/version"
  - "/about"
  - "/bukkit:ver"
  - "/bukkit:version"
  - "/bukkit:about"
  - "/icanhasbukkit"
